name: Sync Materials to Tianyi
on:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy . my-alist:/NJUIS-Resources --progress --stats 1m

