name: Sync Materials to Tianyi
on:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Sync via rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: sync ./ my-alist:/NJUIS-Resources --progress --exclude ".git/**" --exclude ".github/**"
